name: Changelog
on:
  push:
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
