export const responseMock = {
  additional_services: ['signature_delivery'],
  cancel_url: 'http://example.com/cancel',
  created_at: '2021-01-21T17:22:08.818747',
  destination: null,
  id: 42,
  insurance: null,
  internal_reference: null,
  objects: [
    {
      current_packing: [],
      depth: '2',
      details: {
        creation_date: null,
        creator: 'Robert Irwin',
        is_cites: false,
        is_fragile: false,
        materials: [],
        notes: 'notes',
        title: "It's just jazz",
      },
      height: '24',
      images: [],
      internal_reference: null,
      public_reference: null,
      subtype: 'painting_unframed',
      type: 'art',
      unit_of_measurement: 'in',
      value: '100.00',
      value_currency: 'USD',
      weight: '1',
      weight_unit: 'lb',
      width: '36',
    },
  ],
  origin: {
    access_restrictions: [],
    address_line_1: '11 W 53rd St',
    address_line_2: null,
    address_line_3: null,
    city: 'New York',
    contacts: [
      {
        email_address: 'mary@example.com',
        name: 'Mary Quinn Sullivan',
        phone_number: '(333) 333-3333',
      },
    ],
    country: 'US',
    postal_code: '10019',
    region: 'NY',
    title: 'Warehouse',
  },
  payment_process: 'invoicing',
  preferred_quote_types: [],
  private_token: '6f76b6e1-ce25-43a9-b4ea-2ceaac24ec7e',
  public_reference: null,
  shipping_notes: null,
  shortcode: 'DEMO-B49SVZ',
  status: 'new',
  success_url: 'http://example.com/success',
  updated_at: '2021-01-21T17:22:10.129653',
  url: 'https://book.arta.io/b/42/6f76b6e1-ce25-43a9-b4ea-2ceaac24ec7e',
};

export const createPayload = {
  additional_services: ['signature_delivery'],
  cancel_url: 'http://example.com/cancelled',
  destination: {
    access_restrictions: ['stairs_only'],
    address_line_1: '11 W 53rd St',
    address_line_2: 'string',
    address_line_3: 'string',
    city: 'New York',
    region: 'NY',
    postal_code: '10019',
    country: 'US',
    title: 'Warehouse',
    contacts: [
      {
        name: 'Mary Quinn Sullivan',
        email_address: 'mary@example.com',
        phone_number: '(333) 333-3333',
      },
    ],
  },
  insurance: 'arta_transit_insurance',
  internal_reference: 'Purchase Order: 2801',
  objects: [
    {
      internal_reference: 'Accession ID: 823',
      current_packing: ['no_packing'],
      depth: '3',
      details: {
        materials: ['canvas'],
        creation_date: '1980',
        creator: 'Bob Smithson',
        notes: 'Artist signature in the lower left corner',
        title: 'Black Rectangle',
        is_fragile: false,
        is_cites: false,
      },
      height: '32',
      images: ['http://example.com/image.jpg'],
      public_reference: 'Round Smithson work',
      subtype: 'painting_unframed',
      width: '15',
      unit_of_measurement: 'in',
      weight: '3.0',
      weight_unit: 'lb',
      value: '2500',
      value_currency: 'USD',
    },
  ],
  origin: {
    address_line_1: '87 Richardson St',
    city: 'Brooklyn',
    region: 'NY',
    postal_code: '11249',
    country: 'US',
    title: 'Gallery',
    contacts: [
      {
        name: 'Rachel Egistrar',
        email_address: 'registrar@example.com',
        phone_number: '(212) 234-5678',
      },
    ],
  },
  preferred_quote_types: ['parcel'],
  public_reference: 'Order #1437',
  shipping_notes: 'New customer',
  success_url: 'http://example.com/cancelled',
};
